### ISSUE TITLE
Error with new Enum implementation

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#103]
We where using Enums before `0.7.1` and it worked well, but now after switching to the new syntax getting the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "third_party/python/graphene/core/schema.py", line 128, in introspect
    return self.execute(introspection_query).data
  File "third_party/python/graphene/core/schema.py", line 123, in execute
    kwargs = dict(kwargs, request=request, root=root, args=args, schema=self.schema)
  File "third_party/python/graphene/core/schema.py", line 86, in schema
    subscription=self.T(self.subscription))
  File "third_party/python/graphene/core/schema.py", line 22, in __init__
    super(GraphQLSchema, self).__init__(*args, **kwargs)
  File "third_party/python/graphql/core/type/schema.py", line 42, in __init__
    self._type_map = self._build_type_map()
  File "third_party/python/graphql/core/type/schema.py", line 91, in _build_type_map
    type_map = type_map_reducer(type_map, type)
  File "third_party/python/graphql/core/type/schema.py", line 131, in type_map_reducer
    reduced_map = type_map_reducer(reduced_map, getattr(field, 'type', None))
  File "third_party/python/graphql/core/type/schema.py", line 123, in type_map_reducer
    field_map = type.get_fields()
  File "third_party/python/graphql/core/type/definition.py", line 193, in get_fields
    self._field_map = define_field_map(self, self._fields)
  File "third_party/python/graphql/core/type/definition.py", line 227, in define_field_map
    '{}.{} field type must be Output Type but got: {}.'.format(type, field_name, field.type)
AssertionError: Customer.title field type must be Output Type but got: <enum 'Title'>.
```

The strange thing being is that I can not reproduce the error in an isolated test case. So I wonder if it could be something to do with the Enum backport or something else messing with it? In any case will investigate more.

**Comment by syrusakbary** [comment]
Hi @Globegitter, I'm investigating it right now.
Everything should work fine. Are you using `graphene.Enum` explicitly somewhere? What is the Python version?

**Comment by syrusakbary** [comment]
In the case you where using `graphene.Enum` previously, can you paste here the code for seeing how are you using it?

**Comment by Globegitter** [comment]
@syrusakbary After talking to one of my colleauges, we are apparently doing something ourselves to ensure we have enums available (also using the package enum34), so my guess it is related to that and some issue with the way we are using that and the way graphene is ensuring that enums exist.

Trying to us it as follows now:
```py
class Episode(graphene.Enum):
    NEWHOPE = 4
    EMPIRE = 5
    JEDI = 6


class Some(graphene.ObjectType):
    episode = graphene.Field(Episode)

...
```

I will look into it again tomorrow to identify if there is something that we can do, to resolve that issue or if it would require more.

**Comment by Globegitter** [comment]
Ok it was an error purely on our side - sorry for unnecessarily opening this issue.
