### ISSUE TITLE
Django: ImportError: cannot import name 'ResolveInfo'

### ISSUE THREAD

**Issue by SpyTec** [graphql-python/graphene#1047]
Following the Relay walkthrough I'm getting the following error. Since it's quite cryptic
```py
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2935fa98c8>
Traceback (most recent call last):
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    autoreload.raise_last_exception()
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene_django/__init__.py", line 1, in <module>
    from .types import DjangoObjectType
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene_django/types.py", line 8, in <module>
    import graphene
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene/__init__.py", line 3, in <module>
    from .types import (
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene/types/__init__.py", line 2, in <module>
    from graphql import ResolveInfo
ImportError: cannot import name 'ResolveInfo'
```
`INSTALLED_APPS` here, where `graphql` is an app in my project
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # This will also make the `graphql_schema` management command available
    'graphene_django',
    'debug_toolbar',
    'welcome',
    'api',
    'rest_framework',
    'django.contrib.sites',
    'drf_multiple_model',
    'filters',
    'drf_yasg',
    "django_cron",
    'corsheaders',
    'django_filters',
	# app part of the project
    'graphql',
]
```

**Comment by SpyTec** [comment]
Issue moved to [graphql-python/graphene-django #737](https://github.com/graphql-python/graphene-django/issues/737) via [**ZenHub**](https://www.zenhub.com/)
