### ISSUE TITLE
Error trying to create a custom Scalar type

### ISSUE THREAD

**Issue by defrex** [graphql-python/graphene#105]
I'm trying to create a field type called `Money` that is a decimal in python, and rounds to cents as an integer when it's serialized. As per the docs, this is my class.

```python
from decimal import Decimal

from graphene.core.classtypes import Scalar
from graphql.core.language import ast


class Money(Scalar):
    @staticmethod
    def serialize(value):
        return int(value * Decimal(100))

    @staticmethod
    def parse_literal(node):
        if isinstance(node, ast.IntValue):
            return Decimal(node) / Decimal(100)

    @staticmethod
    def parse_value(value):
        return Decimal(value) / Decimal(100)
```

Given this `ObjectType`.

```python
class Summary(graphene.ObjectType):
    income = graphene.Field(Money())
    allocated = graphene.Field(Money())
    spent = graphene.Field(Money())
    net = graphene.Field(Money())
```

I get the following error.

```
Traceback (most recent call last):
  File "/home/defrex/code/spendwell/apps/users/tests.py", line 16, in test_safe_to_spend
    result = self.graph_query('{ viewer { safeToSpend } }', user=owner)
  File "/home/defrex/code/spendwell/apps/core/tests.py", line 21, in graph_query
    result = schema.execute(query, request_context=request)
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphene/core/schema.py", line 123, in execute
    kwargs = dict(kwargs, request=request, root=root, args=args, schema=self.schema)
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphene/core/schema.py", line 86, in schema
    subscription=self.T(self.subscription))
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphene/core/schema.py", line 22, in __init__
    super(GraphQLSchema, self).__init__(*args, **kwargs)
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphql/core/type/schema.py", line 42, in __init__
    self._type_map = self._build_type_map()
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphql/core/type/schema.py", line 91, in _build_type_map
    type_map = type_map_reducer(type_map, type)
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphql/core/type/schema.py", line 131, in type_map_reducer
    reduced_map = type_map_reducer(reduced_map, getattr(field, 'type', None))
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphql/core/type/schema.py", line 131, in type_map_reducer
    reduced_map = type_map_reducer(reduced_map, getattr(field, 'type', None))
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphql/core/type/schema.py", line 131, in type_map_reducer
    reduced_map = type_map_reducer(reduced_map, getattr(field, 'type', None))
  File "/home/defrex/code/spendwell/.env/lib/python3.5/site-packages/graphql/core/type/schema.py", line 106, in type_map_reducer
    ).format(type.name)
AssertionError: Schema must contain unique named types but contains multiple types named "Money".
```

What am I doing wrong?

**Comment by Globegitter** [comment]
@defrex 

I think if you try:
```py
class Summary(graphene.ObjectType):
    income = graphene.Field(Money)
    allocated = graphene.Field(Money)
    spent = graphene.Field(Money)
    net = graphene.Field(Money)
```

it should work.

**Comment by defrex** [comment]
That did the job, thanks!
