### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by makskant** [graphql-python/graphene#1092]
I can't run a simple example.

The setup is a fresh virtual environment.

requirements.txt file containes one line: `graphene`

Pip freeze outputs:
`aniso8601==6.0.0
graphene==2.1.8
graphql-core==2.2.1
graphql-relay==2.0.0
promise==2.2.1
Rx==1.6.1
six==1.12.0
`
File called **test.py** contains:
```
import graphene


class Query(graphene.ObjectType):
  hello = graphene.String(name=graphene.String(default_value="World"))

  def resolve_hello(self, info, name):
    return 'Hello ' + name


schema = graphene.Schema(query=Query)
result = schema.execute('{ hello }')
print(result.data['hello']) # "Hello World"
```
I am running in terminal after activating venv using `python test.py`

The error 
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import graphene
  File "/Users/MaksimSu/sandbox/venv/lib/python3.7/site-packages/graphene/__init__.py", line 1, in <module>
    from .pyutils.version import get_version
  File "/Users/MaksimSu/sandbox/venv/lib/python3.7/site-packages/graphene/pyutils/version.py", line 5, in <module>
    import subprocess
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 50, in <module>
    import signal
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py", line 4, in <module>
    from enum import IntEnum as _IntEnum
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/Users/MaksimSu/sandbox/app/types.py", line 1, in <module>
    import typing
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 28, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

```

**Comment by denizdogan** [comment]
Are you sure your Python installation is correct? In Python 3.7 the `enum` definitely should have the `IntFlag` class. Have you accidentally installed some third-party libraries in your Homebrew Python that could mess with this?
