### ISSUE TITLE
Nested DRF Serializer raises AttributeError: 'NoneType' object has no attribute '_meta'

### ISSUE THREAD

**Issue by elcolie** [graphql-python/graphene#1116]
I can use `Query` and `Mutation`. But after I add `SerializerMutation`
```python
from graphene_django.rest_framework.mutation import SerializerMutation

from multy_herr.objections.api.serializers import ObjectionSerializer


class ObjectionMutation(SerializerMutation):
    class Meta:
        serializer_class = ObjectionSerializer
        model_operations = ['create', 'update']
        lookup_fields = 'id'

```
`serializers.py`
```python
import datetime
from datetime import datetime as dt
from typing import Any

from actstream import action
from django.conf import settings
from rest_framework import serializers

from multy_herr.objections.models import Objection
from multy_herr.taskapp.celery import report_tweet, auto_hide_tweet
from multy_herr.tweets.api.serializers import TweetSerializer
from multy_herr.tweets.models import Tweet


class ObjectionSerializer(serializers.ModelSerializer):
    tweet_detail = TweetSerializer(read_only=True)

    class Meta:
        model = Objection
        fields = [
            'id',
            'tweet',
            'tweet_detail',
            'hidden',
            'report',
            'detail',
        ]

    def validate_tweet(self, value: Tweet):
        user = self.context['request'].user
        if value.created_by == user:
            raise serializers.ValidationError(detail=f"I know how do you feel...")
        if Objection.objects.filter(tweet=value, created_by=user, hidden=True).exists():
            raise serializers.ValidationError(detail=f"You have hide this tweet already!")
        return value

    def create(self, validated_data: Any) -> Any:
        user = self.context['request'].user
        validated_data['created_by'] = user
        objection = super().create(validated_data)

        # Create `Action`
        tuple_list = action.send(user, verb='objected', action_object=objection, target=validated_data['tweet'])

        if settings.PRODUCTION:
            # Dispatch job to worker and let developers knows the problem
            tweet = validated_data['tweet']
            report_tweet.delay(tweet.id)
            current_dt = dt.utcnow()
            dead_line = current_dt + datetime.timedelta(days=1)
            auto_hide_tweet.apply_async(args=(tweet.id,), eta=dead_line)
        else:
            report_tweet(validated_data['tweet'].id)
        return objection
```

`schema.py`
```python
import graphene
import graphql_jwt

from multy_herr.objections.grapheql.mutations import ObjectionMutation
from multy_herr.objections.grapheql.queries import ObjectionQuery


class Query(ObjectionQuery, graphene.ObjectType):
    pass


class Mutation(graphene.ObjectType):
    token_auth = graphql_jwt.ObtainJSONWebToken.Field()
    verify_token = graphql_jwt.Verify.Field()
    refresh_token = graphql_jwt.Refresh.Field()

    objection = ObjectionMutation.Field() # This line


schema = graphene.Schema(query=Query, mutation=Mutation)
```

Here is my full traceback
```bash
/Users/sarit/.pyenv/versions/multy_herr/bin/python /Users/sarit/mein-codes/multy_herr/manage.py runserver 8000
INFO|21/Dec/2019 14:02:41|Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/sarit/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/sarit/.pyenv/versions/3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sarit/mein-codes/multy_herr/config/urls.py", line 21, in <module>
    from schema import schema
  File "/Users/sarit/mein-codes/multy_herr/schema.py", line 20, in <module>
    schema = graphene.Schema(query=Query, mutation=Mutation)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/schema.py", line 78, in __init__
    self.build_typemap()
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/schema.py", line 167, in build_typemap
    self._type_map = TypeMap(
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 80, in __init__
    super(TypeMap, self).__init__(types)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/type/typemap.py", line 28, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))  # type: ignore
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/type/typemap.py", line 106, in reducer
    field_map = type.fields
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/type/definition.py", line 226, in fields
    return define_field_map(self, self._fields)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/type/definition.py", line 240, in define_field_map
    field_map = field_map()
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/type/typemap.py", line 106, in reducer
    field_map = type.fields
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/type/definition.py", line 226, in fields
    return define_field_map(self, self._fields)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphql/type/definition.py", line 240, in define_field_map
    field_map = field_map()
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 276, in construct_fields_for_type
    field_type = self.get_field_type(map, field.type)
  File "/Users/sarit/.pyenv/versions/multy_herr/lib/python3.8/site-packages/graphene/types/typemap.py", line 337, in get_field_type
    return map.get(type._meta.name)
AttributeError: 'NoneType' object has no attribute '_meta'
```

Here is my `requirements.txt`
```bash
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements.in
#
-e git+git@github.com:justquick/django-activity-stream.git@master#egg=django-activity-stream
-e git+git@github.com:jazzband/django-push-notifications.git@master#egg=django-push-notifications
-e git+git@github.com:elcolie/rest-framework-generic-relations.git@master#egg=rest-framework-generic-relations
alabaster==0.7.12         # via sphinx
amqp==2.5.2               # via kombu
aniso8601==7.0.0          # via graphene
apns2==0.7.1
appnope==0.1.0            # via ipython
argon2-cffi==19.2.0
arrow==0.15.4
asgiref==3.2.3            # via django
attrs==19.3.0             # via pytest
babel==2.7.0              # via flower, sphinx
backcall==0.1.0           # via ipython
billiard==3.6.1.0         # via celery
boto3==1.10.44            # via django-storages
botocore==1.13.44         # via boto3
celery==4.4.0
certifi==2019.11.28       # via requests, sentry-sdk
cffi==1.13.2              # via argon2-cffi, cryptography
chardet==3.0.4            # via requests
collectfast==1.3.1
coreapi==2.3.3
coreschema==0.0.4         # via coreapi
coverage==5.0
cryptography==2.8         # via apns2, http-ece, py-vapid, pywebpush
decorator==4.4.1          # via ipython
defusedxml==0.6.0         # via python3-openid
django-allauth==0.41.0
django-anymail[mailgun]==7.0.0
django-celery-results==1.1.2
django-cors-headers==3.2.0
django-coverage-plugin==1.6.0
django-crispy-forms==1.8.1
django-debug-toolbar==2.1
django-environ==0.4.5
django-extensions==2.2.5
django-extra-fields==2.0.2
django-filter==2.2.0
django-graphql-jwt==0.3.0
django-js-asset==1.2.2    # via django-mptt
django-model-utils==4.0.0
django-mptt==0.10.0
django-redis==4.11.0
django-rest-auth==0.9.5
django-storages[boto3]==1.8
django-templated-mail==1.1.1  # via djoser
django==3.0.1
djangorestframework-jwt==1.11.0
djangorestframework-simplejwt==4.4.0
djangorestframework==3.10.3
djoser==2.0.3
docutils==0.15.2          # via botocore, sphinx
entrypoints==0.3          # via flake8
factory-boy==2.12.0
faker==3.0.0              # via factory-boy
flake8==3.7.9
flower==0.9.3
freezegun==0.3.12
graphene-django==2.7.1
graphene==2.1.8           # via graphene-django
graphql-core==2.2.1       # via django-graphql-jwt, graphene, graphene-django, graphql-relay
graphql-relay==2.0.1      # via graphene
gunicorn==20.0.4
h2==2.6.2                 # via hyper
hpack==3.0.0              # via h2
http-ece==1.1.0           # via pywebpush
hyper==0.7.0              # via apns2
hyperframe==3.2.0         # via h2, hyper
idna==2.8                 # via requests
imagesize==1.1.0          # via sphinx
ipdb==0.12.3
ipython==7.10.2           # via ipdb
itypes==1.1.0             # via coreapi
jedi==0.15.2              # via ipython
jinja2==2.10.3            # via coreschema, sphinx
jmespath==0.9.4           # via boto3, botocore
kombu==4.6.7              # via celery
markdown==3.1.1
markupsafe==1.1.1         # via jinja2
mccabe==0.6.1             # via flake8
model-mommy==2.0.0
more-itertools==8.0.2     # via pytest
oauthlib==3.1.0           # via requests-oauthlib
packaging==19.2           # via pytest, pytest-sugar, sphinx
parso==0.5.2              # via jedi
pexpect==4.7.0            # via ipython
pickleshare==0.7.5        # via ipython
pillow==6.2.1
pluggy==0.13.1            # via pytest
promise==2.3              # via graphene-django, graphql-core, graphql-relay
prompt-toolkit==3.0.2     # via ipython
psycopg2==2.8.4
pubnub==4.1.7
py-vapid==1.7.0           # via pywebpush
py==1.8.0                 # via pytest
pycodestyle==2.5.0        # via flake8
pycparser==2.19           # via cffi
pycryptodomex==3.9.4      # via pubnub
pyflakes==2.1.1           # via flake8
pygments==2.5.2           # via ipython, sphinx
pyjwt==1.7.1              # via apns2, django-graphql-jwt, djangorestframework-jwt, djangorestframework-simplejwt
pytest-django==3.7.0
pytest-sugar==0.9.2
pytest==5.3.2
python-dateutil==2.8.1    # via arrow, botocore, faker, freezegun
python-slugify==4.0.0
python3-openid==3.1.0     # via django-allauth
pytz==2019.3
pywebpush==1.10.1
raven==6.10.0
redis==3.3.11
requests-oauthlib==1.3.0  # via django-allauth
requests==2.22.0          # via coreapi, django-allauth, django-anymail, pubnub, pywebpush, requests-oauthlib, sphinx
rx==1.6.1                 # via graphql-core
s3transfer==0.2.1         # via boto3
sentry-sdk==0.13.5
singledispatch==3.4.0.3   # via graphene-django
six==1.13.0               # via argon2-cffi, cryptography, django-anymail, django-coverage-plugin, django-extensions, django-rest-auth, faker, freezegun, graphene, graphene-django, graphql-core, graphql-relay, promise, pubnub, python-dateutil, singledispatch
snowballstemmer==2.0.0    # via sphinx
sphinx==2.3.0
sphinxcontrib-applehelp==1.0.1  # via sphinx
sphinxcontrib-devhelp==1.0.1  # via sphinx
sphinxcontrib-htmlhelp==1.0.2  # via sphinx
sphinxcontrib-jsmath==1.0.1  # via sphinx
sphinxcontrib-qthelp==1.0.2  # via sphinx
sphinxcontrib-serializinghtml==1.1.3  # via sphinx
sqlparse==0.3.0           # via django, django-debug-toolbar
termcolor==1.1.0          # via pytest-sugar
text-unidecode==1.3       # via faker, python-slugify
tornado==5.1.1            # via flower
traitlets==4.3.3          # via ipython
typing-extensions==3.7.4.1  # via collectfast
typing==3.7.4.1           # via collectfast
uritemplate==3.0.1        # via coreapi
urllib3==1.25.7           # via botocore, requests, sentry-sdk
vine==1.3.0               # via amqp, celery
wcwidth==0.1.7            # via prompt-toolkit, pytest
werkzeug==0.16.0

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

Is it `SerializerMutation` support nested serializer?

**Comment by jjorissen52** [comment]
@elcolie did you ever find a resolution to this issue?

**Comment by elcolie** [comment]
Nope. I haven't use it since then
For generic use cases. I switch back to `Django REST Framework` because it does support nested payload, `file`, and various `https methods

**Comment by coler-j** [comment]
Can this issue be re-opened?
