### ISSUE TITLE
name 'relay' is not defined

### ISSUE THREAD

**Issue by yaserrahimi** [graphql-python/graphene#1118]
I install graphene-django now when i want use relay i get this error 
my code is:
```
import graphene
from graphene_django import DjangoObjectType
from graphene_django.filter import DjangoFilterConnectionField
from main.models import Fish


class FishNode(DjangoObjectType):
    class Meta:
        model = Fish
        filter = ['name', 'serial']
        interfaces = (graphene.relay.Node,)


class Query(graphene.ObjectType):
    fish_r = graphene.relay.Node.Field(FishNode)
    all_fish_r = DjangoFilterConnectionField(FishNode)
```
my graphene and graphene-django version:
```
graphene          2.1.8  
graphene-django   2.7.1 
```
error text:
```
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
December 24, 2019 - 08:27:41
Django version 3.0, using settings 'efish.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /graphql
Traceback (most recent call last):
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/django/views/generic/base.py", line 62, in view
    self = cls(**initkwargs)
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/graphene_django/views.py", line 79, in __init__
    schema = graphene_settings.SCHEMA
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/graphene_django/settings.py", line 117, in __getattr__
    val = perform_import(val, attr)
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/graphene_django/settings.py", line 56, in perform_import
    return import_from_string(val, setting_name)
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/site-packages/graphene_django/settings.py", line 70, in import_from_string
    module = importlib.import_module(module_path)
  File "/home/yaser/.virtualenvs/efish/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yaser/Desktop/e-fish/efish/efish/schema.py", line 7, in <module>
    api.fish-relay.schema.Query,
NameError: name 'relay' is not defined
```

**Comment by jkimbo** [comment]
@yaserrahimi what happens if you run `from graphene import relay`?

**Comment by yaserrahimi** [comment]
> @yaserrahimi what happens if you run `from graphene import relay`?

its same like that

**Comment by jkimbo** [comment]
Do you have a folder in your project called `graphene`?

**Comment by yaserrahimi** [comment]
> Do you have a folder in your project called `graphene`?

no i dont have

**Comment by jkimbo** [comment]
@yaserrahimi I can't reproduce the issue. I've tried here: https://repl.it/repls/GrandInfamousDirectory 

Can you create a reproduction so that I can debug it?
