### ISSUE TITLE
cannot import name 'ObjectType' from partially initialized module 'graphene'

### ISSUE THREAD

**Issue by edalongeville** [graphql-python/graphene#1274]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**
When I simply run `import graphene`, I get the following error:
```
>>> import graphene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home//test-graphene/graphene.py", line 1, in <module>
    from graphene import ObjectType, String, Schema
ImportError: cannot import name 'ObjectType' from partially initialized module 'graphene' (most likely due to a circular import)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via a github repo, https://repl.it or similar.

Clone this repo:
https://github.com/edalongeville/test-graphene

Run:
`python3 -m venv .venv`
`source .venv/bin/activate`
`pip install -r requirements.txt`
`python3 graphene.py`

I've been able to reproduce on both Ubuntu Linux and MacOS.

* **What is the expected behavior?**
The code should execute without an issue.

* **What is the motivation / use case for changing the behavior?**
Graphene simply doesn't work.

* **Please tell us about your environment:**

  - Version: Python 3.8.5
  - Platform: Linux (Ubuntu 20.10) and MacOS (latest)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by edalongeville** [comment]
The python file cannot be called graphene.py, which makes sense... closing the issue.
