### ISSUE TITLE
pip install graphene[django] broke my entire app

### ISSUE THREAD

**Issue by varunarora** [graphql-python/graphene#132]
Thank you for the effort you have taken with this effort for Python peeps.

I was only playing around to get my feet wet with graphene, but I think it has caused severe damage. Running `pip install graphene[django]` uninstalled Django 1.4.1, which my HUGE app for running stably for 3 years, caused Django 1.4.1 to be uninstalled and upgraded it to 1.9.4.

Why would any command in the world do such a thing?

Here's what happened when I ran the command:

```
Requirement` already satisfied (use --upgrade to upgrade): graphene[django] in /usr/local/lib/python2.7/dist-packages
  Installing extra requirements: 'django'
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from graphene[django])
Requirement already satisfied (use --upgrade to upgrade): graphql-core>=0.4.9 in /usr/local/lib/python2.7/dist-packages (from graphene[django])
Requirement already satisfied (use --upgrade to upgrade): graphql-relay==0.3.3 in /usr/local/lib/python2.7/dist-packages (from graphene[django])
Downloading/unpacking Django>=1.6.0 (from graphene[django])
  Downloading Django-1.9.4-py2.py3-none-any.whl (6.6MB): 6.6MB downloaded
Downloading/unpacking singledispatch>=3.4.0.3 (from graphene[django])
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Downloading/unpacking graphql-django-view>=1.1.0 (from graphene[django])
  Downloading graphql-django-view-1.1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/graphql-django-view/setup.py) egg_info for package graphql-django-view
    
Installing collected packages: Django, singledispatch, graphql-django-view
  Found existing installation: Django 1.4.1
    Uninstalling Django:
      Successfully uninstalled Django
  Running setup.py install for graphql-django-view
    
Successfully installed Django singledispatch graphql-django-view
```

Now I am trying to reverse this somehow.

**Comment by varunarora** [comment]
So turns out switching back to an old Django version wasn't that hard. And this might be an issue with how pip works. Irrespective, it makes for a very bad user experience.

There is another issue with the choice of Django version. It seems like the app actually requires a minimum of Django 1.8. I got this error AFTER upgrading to 1.6.11:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/varun/Code/opencurriculum/oc_platform/oc_platform/urls.py", line 6, in <module>
    from oc_platform.schema import schema
  File "/home/varun/Code/opencurriculum/oc_platform/oc_platform/schema.py", line 2, in <module>
    import curriculum.schema
  File "/home/varun/Code/opencurriculum/oc_platform/curriculum/schema.py", line 2, in <module>
    from graphene.contrib.django.filter.fields import DjangoFilterConnectionField
  File "/usr/local/lib/python2.7/dist-packages/graphene/contrib/django/filter/fields.py", line 2, in <module>
    from .utils import get_filtering_args_from_filterset, get_filterset_class
  File "/usr/local/lib/python2.7/dist-packages/graphene/contrib/django/filter/utils.py", line 4, in <module>
    from .filterset import custom_filterset_factory, setup_filterset
  File "/usr/local/lib/python2.7/dist-packages/graphene/contrib/django/filter/filterset.py", line 7, in <module>
    from django_filters import Filter, MultipleChoiceFilter
  File "/usr/local/lib/python2.7/dist-packages/django_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/usr/local/lib/python2.7/dist-packages/django_filters/filterset.py", line 19, in <module>
    from .filters import (Filter, CharFilter, BooleanFilter, BaseInFilter, BaseRangeFilter,
  File "/usr/local/lib/python2.7/dist-packages/django_filters/filters.py", line 16, in <module>
    from .fields import (
  File "/usr/local/lib/python2.7/dist-packages/django_filters/fields.py", line 13, in <module>
    from .utils import handle_timezone
  File "/usr/local/lib/python2.7/dist-packages/django_filters/utils.py", line 4, in <module>
    from django.db.models.expressions import Expression
ImportError: cannot import name Expression
```

**Comment by syrusakbary** [comment]
Hi @varunarora, at first sorry for taking so long in replying... I was in vacations until yesterday.

The error is caused by `django_filter`, not `graphene[django]`. You can try uninstalling it, as is incompatible with Django 1.6, with:
```shell
pip uninstall django-filter
```

Then, importing graphene should work fine :)

Please reopen this issue if not, or if you have any other question.
