### ISSUE TITLE
Problem with OneToOne field

### ISSUE THREAD

**Issue by artel1992** [graphql-python/graphene#1332]
models.py
```python
class User(AbstractUser):
    father_name = models.CharField(max_length=255, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    @property
    def age(self) -> int:
        if self.birth_date:
            age = datetime.date.today() - self.birth_date
            return age.days // 360
        return 0


class Passport(models.Model):
    serial = models.CharField(max_length=5)
    number = models.CharField(max_length=10)
    date_given = models.DateField()
    who_given = models.CharField(max_length=255)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
```
serializers.py
```python
class GroupSerializer(serializers.ModelSerializer):
    id = serializers.IntegerField(read_only=False)

    class Meta:
        model = Group
        fields = ('id', 'name')
        read_only_fields = ['name', ]


class PassportSerializer(serializers.ModelSerializer):
    class Meta:
        model = Passport
        fields = ('serial', 'number', 'date_given', 'who_given')


class UserSerializer(serializers.ModelSerializer):
    groups = serializers.PrimaryKeyRelatedField(many=True, queryset=Group.objects.all())
    passport = PassportSerializer()

    class Meta:
        model = User
        fields = ('id', 'username', 'last_name', 'first_name', 'father_name', 'age', 'password', 'groups', 'passport')
        write_only_fields = ('password',)
```
mutations.py
```python

class UserMutation(SerializerMutation):
    class Meta:
        serializer_class = UserSerializer
        lookup_field = 'id'


class Mutation(graphene.ObjectType):
    user_mutation = UserMutation.Field()
    group_mutation = GroupMutation.Field()
```
After I added passport to schema I got error:
```traceback
Internal Server Error: /api/
Traceback (most recent call last):
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene\types\schema.py", line 124, in add_type
    name = graphene_type._meta.name
AttributeError: 'NoneType' object has no attribute '_meta'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphql\type\definition.py", line 758, in fields
    fields = resolve_thunk(self._fields)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphql\type\definition.py", line 296, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene\types\schema.py", line 299, in create_fields_for_type
    field_type = create_graphql_type(field.type)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene\types\schema.py", line 126, in add_type
    raise TypeError(f"Expected Graphene type, but received: {graphene_type}.")
TypeError: Expected Graphene type, but received: None.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\django\views\generic\base.py", line 63, in view
    self = cls(**initkwargs)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene_django\views.py", line 100, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene_django\settings.py", line 126, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene_django\settings.py", line 65, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene_django\settings.py", line 79, in import_from_string
    module = importlib.import_module(module_path)
  File "c:\users\user\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Projects\Programming\borkov\api\schema.py", line 6, in <module>
    schema = graphene.Schema(
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphene\types\schema.py", line 532, in __init__
    self.graphql_schema = GraphQLSchema(
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphql\type\schema.py", line 210, in __init__
    collect_referenced_types(mutation)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphql\type\schema.py", line 423, in collect_referenced_types
    collect_referenced_types(field.type)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphql\type\schema.py", line 422, in collect_referenced_types
    for field in named_type.fields.values():
  File "c:\users\user\appdata\local\programs\python\python39\lib\functools.py", line 969, in __get__
    val = self.func(instance)
  File "C:\Users\User\.virtualenvs\borkov-Rea4rqcB\lib\site-packages\graphql\type\definition.py", line 760, in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
TypeError: UserMutationPayload fields cannot be resolved. Expected Graphene type, but received: None.
[28/Apr/2021 19:08:59] "GET /api/ HTTP/1.1" 500 188518
```

**Comment by artel1992** [comment]
sorry, I wrote in the wrong place
