### ISSUE TITLE
Race condition when registering certain types?

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#198]
We have started to see intermittent `Schema must contain unique named types but contains multiple types named "Days".`. The same query can fail and when I restart the server it works again. This kind of leads me to believe that there could be some kind of race condition with registering types.

I also looked into the schema itself (as it has grown quite large by now) and it only has one enum type `Days` created. When I do `print(str(graphene.Schema(...))` I see that I have:

```
...
enum Days {
  FRIDAY
  MONDAY
  SATURDAY
  SUNDAY
  THURSDAY
  TUESDAY
  WEDNESDAY
}

type Settings implements Node {
  id: ID!
  ...
  notificationDay: Days
  collectionDay: Days
}

...

enum Interval {
  DAYS
  MONTHS
  WEEKS
  YEARS
}

...
```

which are the only occurrences of the word 'days' in our full schema. So I am not sure how this error can come about. Any ideas?

Here the full stack trace:
```
2016-06-07 14:56:43,311:webapp2.py:1552:ERROR: - Schema must contain unique named types but contains multiple types named "Days".
Traceback (most recent call last):
  File "python/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "python/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "python/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "python/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "python/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "python/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "python/graphql_handler.py", line 114, in post
    variable_values=variables)
  File "python/graphene/core/schema.py", line 123, in execute
    schema=self.schema,
  File "python/graphene/core/schema.py", line 81, in schema
    subscription=self.T(self.subscription))
  File "python/graphene/core/schema.py", line 19, in __init__
    super(GraphQLSchema, self).__init__(*args, **kwargs)
  File "python/graphql/type/schema.py", line 58, in __init__
    self._type_map = self._build_type_map(types)
  File "python/graphql/type/schema.py", line 107, in _build_type_map
    type_map = reduce(type_map_reducer, types, OrderedDict())
  File "python/graphql/type/schema.py", line 159, in type_map_reducer
    reduced_map = type_map_reducer(reduced_map, getattr(field, 'type', None))
  File "python/graphql/type/schema.py", line 159, in type_map_reducer
    reduced_map = type_map_reducer(reduced_map, getattr(field, 'type', None))
  File "python/graphql/type/schema.py", line 134, in type_map_reducer
    ).format(type.name)
AssertionError: Schema must contain unique named types but contains multiple types named "Days".
```

**Comment by Kagandi** [comment]
I am having the same error and it happens inconsistently, sometimes I can run the same queries several times and everything is working and after some point it starts crashing.
I noticed that it is only happening when I am sending multiply asynchronous fetch requests in the same time.

**Comment by syrusakbary** [comment]
That should be fixed in master! Closing the issue.
