### ISSUE TITLE
ImportError: cannot import name 'MiddlewareManager'

### ISSUE THREAD

**Issue by danfairs** [graphql-python/graphene#291]
Hi!

I'm just playing with GraphQL with Django. While running `runserver`, I immediately get a traceback:

```
(unrest) boatman:taxnav dan$ python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10ea1eae8>
Traceback (most recent call last):
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/graphene_django/__init__.py", line 1, in <module>
    from .types import (
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/graphene_django/types.py", line 5, in <module>
    from graphene import ObjectType, Field
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/graphene/__init__.py", line 19, in <module>
    from .types import (
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/graphene/types/__init__.py", line 8, in <module>
    from .schema import Schema
  File "/Users/dan/Envs/unrest/lib/python3.5/site-packages/graphene/types/schema.py", line 2, in <module>
    from graphql import GraphQLSchema, MiddlewareManager, graphql, is_type
ImportError: cannot import name 'MiddlewareManager'

(unrest) boatman:taxnav dan$ pip freeze | grep -i "graph\|django"
Django==1.10
django-filter==0.11.0
django-graphiql==0.4.4
django-model-utils==2.5.2
djangorestframework==3.4.6
graphene==1.0.dev0
graphene-django==1.0.dev20160910000001
graphql-core==0.5.3
graphql-django-view==1.3
graphql-relay==0.4.4
```
What's up here? Thanks!

**Comment by femesq** [comment]
Probably because `graphql-core`'s version. Try going to `1.0.dev` for this package too.
If you need `middleware`, wait for this [https://github.com/graphql-python/graphql-django-view/issues/14] to get solved.

Good luck,

**Comment by syrusakbary** [comment]
Hi @danfairs, the middleware manager no longer exists in the 1.0 version.
The docs will be updated around this week as the stable version for 1.0 is going to be released soon.

**Comment by danfairs** [comment]
Updating the version fixed it for me - thanks! I'll leave this issue open if you're using it to track docs changes.

**Comment by syrusakbary** [comment]
*removed my comment as I pointed in the bad direction and could mislead other people having this problem.*

Closing the issue :)
