### ISSUE TITLE
Type has no attribute 'name' when List is class attribute (master)

### ISSUE THREAD

**Issue by benblippar** [graphql-python/graphene#292]
```
>>> import graphene
>>> graphene.List(graphene.Int())
<graphene.types.structures.List object at 0x1041ee780>
>>> class Example(graphene.ObjectType):
...  a = graphene.List(graphene.Int())
...
>>> class Query(graphene.ObjectType):
...  example = graphene.Field(Example)
...
>>> scheme = graphene.Schema(Query)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/schema.py", line 45, in __init__
    self.build_typemap()
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/schema.py", line 102, in build_typemap
    self._type_map = TypeMap(initial_types, auto_camelcase=self.auto_camelcase)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 45, in __init__
    super(TypeMap, self).__init__(types)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphql/type/typemap.py", line 16, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 53, in reducer
    return self.graphene_reducer(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 65, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 134, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 198, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 53, in reducer
    return self.graphene_reducer(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 65, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 134, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 198, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 53, in reducer
    return self.graphene_reducer(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 58, in graphene_reducer
    return self.reducer(map, type.of_type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphene/types/typemap.py", line 54, in reducer
    return GraphQLTypeMap.reducer(map, type)
  File "/Users/ben/.virtualenvs/example/lib/python3.5/site-packages/graphql/type/typemap.py", line 59, in reducer
    if type.name in map:
AttributeError: 'Int' object has no attribute 'name'
```

**Comment by syrusakbary** [comment]
Hi @benblippar, you should use `graphene.List(graphene.Int)` instead of `graphene.List(graphene.Int)`.

`graphene.Int()` is a shortcut for `graphene.Field(graphene.Int)`.

Closing the issue, but feel free to do any comment!

**Comment by benblippar** [comment]
worked it out just before you comment... thanks!

**Comment by warunaeniplex** [comment]
what is this >>> assert _type.graphene_type == type
                         AssertionError
