### ISSUE TITLE
ProcessExecutor fails

### ISSUE THREAD

**Issue by benblippar** [graphql-python/graphene#308]
ERROR|2016-09-30 23:17:10,671|graphql.execution.executor >> An error occurred while resolving field Query.viewer
Traceback (most recent call last):
  File "/Users/ben/.virtualenvs/current/lib/python3.5/site-packages/graphql/execution/executor.py", line 190, in resolve_or_error
    return executor.execute(resolve_fn, source, args, context, info)
  File "/Users/ben/.virtualenvs/current/lib/python3.5/site-packages/graphql/execution/executors/process.py", line 28, in execute
    self.q.put([promise, fn, args, kwargs], False)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 81, in put
    assert not self._closed
AssertionError

**Comment by benblippar** [comment]
Ah this was caused by objects that can't be pickled ... hmm
