### ISSUE TITLE
Cannot pass arguments to Scalar Field

### ISSUE THREAD

**Issue by wenley** [graphql-python/graphene#329]
While typing into the playground, I was unable to specify a schema with arguments to a scalar field. Reproduces locally.

Minimal code to reproduce:
```
import graphene

class Query(graphene.ObjectType):
    argumented_string = graphene.Field(graphene.String(), arg = graphene.Int())

    def resolve_argumented_string(self, args, context, info):
        return 'some person' + str(args)

schema = graphene.Schema(query=Query)
```

I expect to be able to (eventually) pass the following query document:
```
{
  argumentedString(arg: 10)
}
```

But it instead throws the following error:
```
python graphene_test.py
Traceback (most recent call last):
  File "graphene_test.py", line 9, in <module>
    schema = graphene.Schema(query=Query)
  File "/usr/local/lib/python2.7/site-packages/graphene/types/schema.py", line 38, in __init__
    self.build_typemap()
  File "/usr/local/lib/python2.7/site-packages/graphene/types/schema.py", line 85, in build_typemap
    self._type_map = TypeMap(initial_types, auto_camelcase=self.auto_camelcase)
  File "/usr/local/lib/python2.7/site-packages/graphene/types/typemap.py", line 50, in __init__
    super(TypeMap, self).__init__(types)
  File "/usr/local/lib/python2.7/site-packages/graphql/type/typemap.py", line 16, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))
  File "/usr/local/lib/python2.7/site-packages/graphene/types/typemap.py", line 58, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/site-packages/graphene/types/typemap.py", line 70, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/usr/local/lib/python2.7/site-packages/graphene/types/typemap.py", line 144, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/usr/local/lib/python2.7/site-packages/graphene/types/typemap.py", line 208, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python2.7/site-packages/graphene/types/typemap.py", line 59, in reducer
    return GraphQLTypeMap.reducer(map, type)
  File "/usr/local/lib/python2.7/site-packages/graphql/type/typemap.py", line 59, in reducer
    if type.name in map:
AttributeError: 'String' object has no attribute 'name'
```

If `argumented_string` is an `ObjectType` with the expected `name` field, it works just fine.

**Comment by ekampf** [comment]
Change code to:
```
argumented_string = graphene.Field(graphene.String, arg=graphene.Int())
```

**Comment by ekampf** [comment]
`Field()` expects a type not an instance...

**Comment by wenley** [comment]
Augh, thanks!
