### ISSUE TITLE
Not compatible with latest version of django-filter (1.15)

### ISSUE THREAD

**Issue by rattrayalex** [graphql-python/graphene#344]
Hi, 

I'm not sure which patch of django-filter v.1.15.x causes this, but following the django tutorial causes an error related to `filter_order`. 

Here's a traceback:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/code/django_api_project/urls.py", line 21, in <module>
    from .schema import schema
  File "/code/django_api_project/schema.py", line 3, in <module>
    import app.schema
  File "/code/app/schema.py", line 28, in <module>
    class Query(ObjectType):
  File "/code/app/schema.py", line 33, in Query
    all_jobs = DjangoFilterConnectionField(JobNode)
  File "/usr/local/lib/python3.5/site-packages/graphene_django/filter/fields.py", line 20, in __init__
    self.filterset_class = get_filterset_class(filterset_class, **meta)
  File "/usr/local/lib/python3.5/site-packages/graphene_django/filter/utils.py", line 32, in get_filterset_class
    return custom_filterset_factory(**meta)
  File "/usr/local/lib/python3.5/site-packages/graphene_django/filter/filterset.py", line 127, in custom_filterset_factory
    'Meta': meta_class
  File "/usr/local/lib/python3.5/site-packages/graphene_django/filter/filterset.py", line 55, in __new__
    new_class = super(GrapheneFilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/usr/local/lib/python3.5/site-packages/django_filters/filterset.py", line 224, in __new__
    filters[order_by_field] = new_class.get_ordering_filter(opts, filters)
  File "/usr/local/lib/python3.5/site-packages/django_filters/filterset.py", line 375, in get_ordering_filter
    "'order_by' is not compatible with the 'fields' dict syntax. Use OrderingFilter instead."
AssertionError: 'order_by' is not compatible with the 'fields' dict syntax. Use OrderingFilter instead.
```

This was fixed for me by downgrading to django-filter v.1.14.0

**Comment by yfilali** [comment]
@rattrayalex you should probably move this issue to https://github.com/graphql-python/graphene-django/issues as it is a django integration issue and not a core graphene issue.

Also, this seems a duplicate of https://github.com/graphql-python/graphene-django/issues/8

**Comment by rattrayalex** [comment]
Ah, yes it is a dup. Apologies.
