### ISSUE TITLE
Assertion Errors After Commit 5e0923b5

### ISSUE THREAD

**Issue by zeroSteiner** [graphql-python/graphene#390]
After [this commit](https://github.com/graphql-python/graphene/blob/5e0923b56073f42ce25da6628c46ebed120b0654/graphene/types/typemap.py#L72) I have started to get Assertion errors when I load my model. I'm using the snippet below to update the Connection to allow me to add a `total` field into it. This may not be the best way to accomplish the task and I'm open to alternatives but this is how I was able to make it work up until the aforementioned commit.

My code that appears to be triggering this error is:
```python
class SQLAlchemyConnectionField(graphene_sqlalchemy.SQLAlchemyConnectionField):
	def __init__(self, node, *args, **kwargs):
		node = self.connection_factory(node)
		super(SQLAlchemyConnectionField, self).__init__(node, *args, **kwargs)

	@classmethod
	def connection_factory(cls, node):
		connection_type = type(
			node.__name__ + 'Connection',
			(graphene.relay.Connection,),
			{
				'Meta': type('Meta', (), {'node': node}),
				'total': graphene.Int(),
			}
		)
		return connection_type
```

Traceback snippet:
```
Traceback (most recent call last):
  File "KingPhisherServer", line 50, in <module>
    from king_phisher.server import build
  File "/home/steiner/repos/king-phisher/king_phisher/server/build.py", line 39, in <module>
    from king_phisher.server.server import KingPhisherRequestHandler, KingPhisherServer
  File "/home/steiner/repos/king-phisher/king_phisher/server/server.py", line 52, in <module>
    from king_phisher.server import server_rpc
  File "/home/steiner/repos/king-phisher/king_phisher/server/server_rpc.py", line 44, in <module>
    from king_phisher.server import graphql
  File "/home/steiner/repos/king-phisher/king_phisher/server/graphql.py", line 484, in <module>
    schema = Schema()
  File "/home/steiner/repos/king-phisher/king_phisher/server/graphql.py", line 469, in __init__
    super(Schema, self).__init__(**kwargs)
  File "/usr/lib/python3.5/site-packages/graphene/types/schema.py", line 39, in __init__
    self.build_typemap()
  File "/usr/lib/python3.5/site-packages/graphene/types/schema.py", line 97, in build_typemap
    self._type_map = TypeMap(initial_types, auto_camelcase=self.auto_camelcase)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 56, in __init__
    super(TypeMap, self).__init__(types)
  File "/usr/lib/python3.5/site-packages/graphql/type/typemap.py", line 16, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 76, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 147, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 208, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 76, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 147, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 208, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 76, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 147, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 208, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 76, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 147, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 208, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 76, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 147, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 208, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/lib/python3.5/site-packages/graphene/types/typemap.py", line 73, in graphene_reducer
    assert _type.graphene_type == type
AssertionError
```

**Comment by syrusakbary** [comment]
It seems you have multiple `node.__name__ + 'Connection'` types in your schema. (same name, different type).

**Comment by zeroSteiner** [comment]
You're right, that appears to be the issue. Thanks for pointing that out.
