### ISSUE TITLE
Adding a mutation to a schema causes an error

### ISSUE THREAD

**Issue by Waitak** [graphql-python/graphene#414]
I have a schema that contains several queries, all of which are working fine. When I try to add a mutation, Graphiql gives me the following:

    TypeError: Cannot read property 'reduce' of null
        at keyValMap (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:11:8487)
        at f (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:14:4198)
        at fields (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:14:3422)
        at resolveThunk (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:12:8942)
        at defineFieldMap (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:12:9648)
        at exports.GraphQLObjectType.e.getFields (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:12:14824)
        at http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:13:12915
        at typeMapReducer (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:13:13087)
        at Array.reduce (native)
        at new e (http://cdn.jsdelivr.net/graphiql/0.7.8/graphiql.min.js:13:16020)

The mutation class is very straightforward:

    class SomeClass(graphene_django.DjangoObjectType):
        class Meta:
            model = SomeModel
            interface = (relay.Node, )

    class CreateSomething(graphene.Mutation):
        class Input:
            some_field = graphene.String()
            some_other_field = graphene.String()

        ok = graphene.Boolean()
        some_obj = graphene.Field(lambda: SomeClass)

        def mutate(self, args, context, info):
            obj = SomeModel(some_field=args.get('some_field'), some_other_field=args.get('some_other_field'))
            return CreateSomething(ok=True, some_obj=obj)

    class MyMutations(graphene.ObjectType):
        create_something = CreateSomething.Field()

as is the code that includes it in the schema:

    class MyMutations(MyMutations, graphene.ObjectType):
        pass

    schema = graphene.Schema(query=MyQueries, mutation=MyMutations)

What am I missing?

**Comment by Waitak** [comment]
I think that I've solved it. The parent class of MyMutations needs to be AbstractType and not ObjectType.
