### ISSUE TITLE
Graphene +  SQL Alchemy+scoped_session, Can't reconnect until invalid transaction is rolled back

### ISSUE THREAD

**Issue by bochuxt** [graphql-python/graphene#479]
I am using Graphene +  SQL Alchemy for schema query. but it always return the following issue saying unable to reconnect.

    engine = create_engine(
        "mysql+mysqldb://{}:{}@{}:{}/{}".format(username, password, host, port, dbname),
        isolation_level="READ UNCOMMITTED",
        pool_size=POOL_DEFAULT,
        pool_recycle=1,
        max_overflow=sys.maxsize,
        #poolclass=NullPool

    )

session_factory = sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine)

# db_session = scoped_session(session_factory)
Session = scoped_session(session_factory)

[2017-05-25 21:20:40 +0000] [1034] [DEBUG] POST /graphql
ERROR:graphql.execution.executor:An error occurred while resolving field Query.focusInCoworkerById
Traceback (most recent call last):
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1112, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
    conn = self._revalidate_connection()
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv3/lib/python3.4/site-packages/graphql/execution/executor.py", line 200, in resolve_or_error
    return executor.execute(resolve_fn, source, args, context, info)
  File "/app/venv3/lib/python3.4/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/app/ql/dao/schema.py", line 340, in resolve_focusInCoworkerById
    return  queryfocusInCoworker.filter_by(hubot_id=args.get('coworker_id')).all()
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
    None, None)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
    conn = self._revalidate_connection()
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT dashboard_hubot_vitals.id AS dashboard_hubot_vitals_id, dashboard_hubot_vitals.vital_id AS dashboard_hubot_vitals_vital_id, dashboard_hubot_vitals.hubot_id AS dashboard_hubot_vitals_hubot_id \nFROM dashboard_hubot_vitals \nWHERE dashboard_hubot_vitals.hubot_id = %s'] [parameters: [{}]]
[2017-05-25 21:20:40 +0000] [1034] [DEBUG] Closing connection.
[2017-05-25 21:20:42 +0000] [1034] [DEBUG] GET /graphiql
[2017-05-25 21:20:42 +0000] [1034] [DEBUG] Closing connection.
[2017-05-25 21:20:42 +0000] [1032] [DEBUG] GET /graphiql/graphiql.css
[2017-05-25 21:20:42 +0000] [1033] [DEBUG] GET /graphiql/graphiql.min.js
[2017-05-25 21:20:42 +0000] [1032] [DEBUG] Closing connection.
[2017-05-25 21:20:42 +0000] [1033] [DEBUG] Closing connection.
[2017-05-25 21:20:44 +0000] [1033] [DEBUG] POST /graphql
[2017-05-25 21:20:44 +0000] [1033] [DEBUG] Closing connection.
[2017-05-25 21:20:48 +0000] [1034] [DEBUG] POST /graphql
ERROR:graphql.execution.executor:An error occurred while resolving field Query.focusInCoworkerById
Traceback (most recent call last):
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1112, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
    conn = self._revalidate_connection()
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv3/lib/python3.4/site-packages/graphql/execution/executor.py", line 200, in resolve_or_error
    return executor.execute(resolve_fn, source, args, context, info)
  File "/app/venv3/lib/python3.4/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/app/ql/dao/schema.py", line 340, in resolve_focusInCoworkerById
    return  queryfocusInCoworker.filter_by(hubot_id=args.get('coworker_id')).all()
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
    None, None)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
    conn = self._revalidate_connection()
  File "/app/venv3/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT dashboard_hubot_vitals.id AS dashboard_hubot_vitals_id, dashboard_hubot_vitals.vital_id AS dashboard_hubot_vitals_vital_id, dashboard_hubot_vitals.hubot_id AS dashboard_hubot_vitals_hubot_id \nFROM dashboard_hubot_vitals \nWHERE dashboard_hubot_vitals.hubot_id = %s'] [parameters: [{}]]
[2017-05-25 21:20:48 +0000] [1034] [DEBUG] Closing connection.
[2017-05-25 21:20:49 +0000] [1032] [DEBUG] POST /graphql

**Comment by jkimbo** [comment]
Hi @bochuxt . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by stan-sack** [comment]
@bochuxt did you ever deal with this? @jkimbo This is definitely still an issue

**Comment by jkimbo** [comment]
@stan-sack I don't think this is an issue with Graphene since it is backend agnostic and doesn't do anything special to support SQLAlchemy. If you have a reproducible example I could take a look at it?
