### ISSUE TITLE
'context' is not defined with 2.0.dev

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene#534]
error with latest from master graphene-django>=2.0.dev2017073101    
```
System check identified no issues (0 silenced).
August 27, 2017 - 23:27:56
Django version 1.11.4, using settings 'config.settings.local'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
DJANGO DEBUG TOOLBAR ___ OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 209, in complete_value_catching_error
    completed = complete_value(exe_context, return_type, field_asts, info, result)
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 260, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: name 'context' is not defined
[27/Aug/2017 23:28:17] "GET /graphql?query=%7B%0A%20me%7B%0A%20%20uuid%0A%7D%20%0A%7D&operationName=null HTTP/1.1" 200 4155
DJANGO DEBUG TOOLBAR ___ OK
[27/Aug/2017 23:28:18] "POST /graphql? HTTP/1.1" 200 28017
DJANGO DEBUG TOOLBAR ___ OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 209, in complete_value_catching_error
    completed = complete_value(exe_context, return_type, field_asts, info, result)
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 260, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: name 'context' is not defined
[27/Aug/2017 23:28:22] "POST /graphql? HTTP/1.1" 200 111
DJANGO DEBUG TOOLBAR ___ OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 209, in complete_value_catching_error
    completed = complete_value(exe_context, return_type, field_asts, info, result)
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 260, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: name 'context' is not defined
[27/Aug/2017 23:28:31] "POST /graphql? HTTP/1.1" 200 111

```

**Comment by syrusakbary** [comment]
Hi @japrogramer, You will need to use the latest version of `graphene-django`.

```bash
pip install "graphene-django>=2.0.dev"
```

Let me know if this works!

**Comment by japrogramer** [comment]
I was still using context instead of info.context now it works 👍
