### ISSUE TITLE
import graphene not working

### ISSUE THREAD

**Issue by creativesands** [graphql-python/graphene#546]
`import graphene` gives me the following error

```
Traceback (most recent call last):
  File ".../app.py", line 1, in <module>
    import graphene
  File ".../anaconda/lib/python3.6/site-packages/graphene/__init__.py", line 3, in <module>
    from .types import (
  File ".../anaconda/lib/python3.6/site-packages/graphene/types/__init__.py", line 2, in <module>
    from graphql import ResolveInfo
ImportError: cannot import name 'ResolveInfo'
```

**Comment by syrusakbary** [comment]
Hi, 
It seems you are using Graphene 2.0.dev, so you will need the latest package of graphql-core that have `ResolveInfo`.

You can solve the issue by doing `pip install "graphql-core>=2.0.dev"`

**Comment by dongyuzheng** [comment]
I have the same issue:

```powershell
(venv) PS D:\backend\backend> python .\manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x04302D20>
Traceback (most recent call last):
  File "D:\backend\venv\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "D:\backend\venv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "D:\backend\venv\lib\site-packages\django\utils\autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "D:\backend\venv\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\backend\venv\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "D:\backend\venv\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\backend\venv\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "D:\backend\venv\lib\site-packages\django\apps\config.py", line 94, in create
    module = import_module(entry)
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:\backend\venv\lib\site-packages\graphene_django\__init__.py", line 1, in <module>
    from .types import (
  File "D:\backend\venv\lib\site-packages\graphene_django\types.py", line 4, in <module>
    from graphene import Field
  File "D:\backend\venv\lib\site-packages\graphene\__init__.py", line 3, in <module>
    from .types import (
  File "D:\backend\venv\lib\site-packages\graphene\types\__init__.py", line 2, in <module>
    from graphql import ResolveInfo
ImportError: cannot import name 'ResolveInfo'
(venv) PS D:\backend\backend> pip freeze
colorama==0.3.9
decorator==4.1.2
Django==1.11.5
graphene==2.0.dev20170802065539
graphene-django==2.0.dev2017083101
graphql-core==2.0.dev20170801051721
graphql-relay==0.4.5
ipdb==0.10.3
ipython==6.2.0
ipython-genutils==0.2.0
iso8601==0.1.12
jedi==0.10.2
pickleshare==0.7.4
promise==2.1.dev0
prompt-toolkit==1.0.15
Pygments==2.2.0
pytz==2017.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
traitlets==4.3.2
typing==3.6.2
wcwidth==0.1.7
(venv) PS D:\backend\backend> python --version
Python 3.6.2
(venv) PS D:\backend\backend>
```

**Comment by jkimbo** [comment]
@leebenson it's a result of how Python find modules: https://docs.python.org/3/tutorial/modules.html#the-module-search-path

**Comment by mbrochh** [comment]
I had this issue as well.

My only dependency in `requirements.txt` was: `graphene-django==2.1.0`

According to pip freeze, it seems, this has installed `graphql-core==3.0.0a0`. I downgraded that to `pip install "graphql-core<3.0.0a0"` and thus got rid of the issue.

Is this a bug with the latest graphene-django package? Is it referring to a 3.0 version of graphql-core prematurely?

**Comment by jkimbo** [comment]
@mbrochh if you install the latest version of graphene-django (2.4.0) it should resolve graphql-core correctly.

**Comment by qlibp** [comment]
this may also help: https://stackoverflow.com/questions/59582142/import-cannot-import-name-resolveinfo-from-graphql-error-when-using-newest
