### ISSUE TITLE
Type error (is_type_of() missing argument)

### ISSUE THREAD

**Issue by LittleWolfWerewolf** [graphql-python/graphene#569]
Schema:

```
class User(SQLAlchemyObjectType):
    class Meta:
        model = Usermodel

class Query(graphene.ObjectType):
    users = graphene.List(User)

    def resolve_users(self, info):
        query = User.get_query(info)  # SQLAlchemy query
        return query.all()
```

Model:

```
class User(db.Model):
    __tablename__ = "user"

    user_id = Column(Integer, primary_key=True)
    user_name = Column(String(256), nullable=False, unique=True)
    user_username = Column(String(256), nullable=False, unique=True)
    user_password = Column(String(256), nullable=False)

    def __str__(self):
        return self.user_name
```

Query from graphiql:
```
query {
  users {
    userId
  }
}
```

Log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executor.py", line 215, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executor.py", line 290, in complete_value
    return complete_object_value(exe_context, return_type, field_asts, info, result)
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executor.py", line 380, in complete_object_value
    if return_type.is_type_of and not return_type.is_type_of(result, info):
TypeError: is_type_of() missing 1 required positional argument: 'info'
```

**Comment by jkimbo** [comment]
Hi @LittleWolfWerewolf . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
