### ISSUE TITLE
import graphene issue

### ISSUE THREAD

**Issue by aniagarwal97** [graphql-python/graphene#667]
I using python 3.5.2 when i am trying to import graphene in my shell it is showing me error 
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/graphene/__init__.py", line 1, in <module>
    from .pyutils.version import get_version
  File "/usr/local/lib/python3.5/dist-packages/graphene/pyutils/version.py", line 5, in <module>
    import subprocess
  File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/usr/lib/python3.5/signal.py", line 4, in <module>
    from enum import IntEnum as _IntEnum
  File "/home/aniruddh/graphql/enum.py", line 3, in <module>
    class Episode(graphene.Enum):
AttributeError: module 'graphene' has no attribute 'Enum'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, re, pwd, grp, os, time
  File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/usr/lib/python3.5/signal.py", line 4, in <module>
    from enum import IntEnum as _IntEnum
  File "/home/aniruddh/graphql/enum.py", line 1, in <module>
    import graphene
  File "/usr/local/lib/python3.5/dist-packages/graphene/__init__.py", line 3, in <module>
    from .types import (
  File "/usr/local/lib/python3.5/dist-packages/graphene/types/__init__.py", line 2, in <module>
    from graphql import ResolveInfo
  File "/usr/local/lib/python3.5/dist-packages/graphql/__init__.py", line 27, in <module>
    from .graphql import (
  File "/usr/local/lib/python3.5/dist-packages/graphql/graphql.py", line 1, in <module>
    from .execution import ExecutionResult, execute
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/__init__.py", line 21, in <module>
    from .executor import execute, subscribe
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executor.py", line 8, in <module>
    from promise import Promise, promise_for_dict, is_thenable
  File "/usr/local/lib/python3.5/dist-packages/promise/__init__.py", line 18, in <module>
    from .promise import (
  File "/usr/local/lib/python3.5/dist-packages/promise/promise.py", line 14, in <module>
    from .utils import deprecated, integer_types, string_types, text_type, binary_type, warn
  File "/usr/local/lib/python3.5/dist-packages/promise/utils.py", line 2, in <module>
    import inspect
  File "/usr/lib/python3.5/inspect.py", line 2349, in <module>
    class _ParameterKind(enum.IntEnum):
AttributeError: module 'enum' has no attribute 'IntEnum'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/graphene/__init__.py", line 1, in <module>
    from .pyutils.version import get_version
  File "/usr/local/lib/python3.5/dist-packages/graphene/pyutils/version.py", line 5, in <module>
    import subprocess
  File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/usr/lib/python3.5/signal.py", line 4, in <module>
    from enum import IntEnum as _IntEnum
  File "/home/aniruddh/graphql/enum.py", line 3, in <module>
    class Episode(graphene.Enum):
AttributeError: module 'graphene' has no attribute 'Enum'
```
Please help me with the issue.

**Comment by jkimbo** [comment]
@aniagarwal97 also make sure that you haven't got any folders or files named as `graphql` or `graphene` since that will override the `grapqhl` and `graphene` modules.

**Comment by jkimbo** [comment]
Closing this issue. I can reopen it again if more information is provided.

**Comment by Aashish75** [comment]
I am getting the same error when i try to import numpy and tensorflow, in python 3.
>>> import numpy
0   5
1   6
2   7
3   8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'numpy'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, re, pwd, grp, os, time
  File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/usr/lib/python3.5/signal.py", line 4, in <module>
    from enum import IntEnum as _IntEnum
ImportError: cannot import name 'IntEnum'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'numpy'

Please help

**Comment by jkimbo** [comment]
@Aashish75 that error looks like an issue with numpy or tensorflow and doesn't look related Graphene. You might find more help by posting a question on stackoverflow.

**Comment by Aashish75** [comment]
@jkimbo Yes, its not specifically related to Graphene. But I dont think the source of error is from tensorflow or numpy. 
File "/usr/lib/python3.5/signal.py", line 4, in
from enum import IntEnum as _IntEnum
ImportError: cannot import name 'IntEnum'
Got the same error for both. I am not able to resolve this. Please help.

**Comment by jkimbo** [comment]
@Aashish75 you could try this: https://stackoverflow.com/a/52159062/1165117 ?

**Comment by Aashish75** [comment]
I tried it @jkimbo . I get 
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (1.1.6)
when I install enum34. Again, same error repeats
