### ISSUE TITLE
Hello world example not working

### ISSUE THREAD

**Issue by ahujamoh** [graphql-python/graphene#689]
Dear Contributors,

I was trying the graphql example given on the website: https://graphql.org/code/#python

I copied the code exactly.

```python
import graphene
class Query(graphene.ObjectType):
  hello = graphene.String()

  def resolve_hello(self, args, context, info):
    return 'Hello world!'

schema = graphene.Schema(query=Query)
result = schema.execute('{ hello }')
print(result.data['hello'])
```

Also having installed graphene using pip(angular is name of my virtualenv)
```bash
> pip install graphene
Requirement already satisfied: graphene in /Users/mohit/virtualenvs/angular/lib/python2.7/site-packages
Requirement already satisfied: six<2,>=1.10.0 in /Users/mohit/virtualenvs/angular/lib/python2.7/site-packages (from graphene)
Requirement already satisfied: graphql-core<3,>=2.0 in /Users/mohit/virtualenvs/angular/lib/python2.7/site-packages (from graphene)
Requirement already satisfied: promise<3,>=2.1 in /Users/mohit/virtualenvs/angular/lib/python2.7/site-packages (from graphene)
Requirement already satisfied: graphql-relay<1,>=0.4.5 in /Users/mohit/virtualenvs/angular/lib/python2.7/site-packages (from graphene)
Requirement already satisfied: rx>=1.6.0 in /Users/mohit/virtualenvs/angular/lib/python2.7/site-packages (from graphql-core<3,>=2.0->graphene)
Requirement already satisfied: typing in /Users/mohit/virtualenvs/angular/lib/python2.7/site-packages (from promise<3,>=2.1->graphene)
(angular)
```

I tried running `python hello.py`, but got the following error. 
```bash
> python hello.py
No handlers could be found for logger "graphql.execution.executor"
Traceback (most recent call last):
  File "/Users/mohit/virtualenvs/angular/lib/python2.7/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/mohit/virtualenvs/angular/lib/python2.7/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
graphql.error.located_error.GraphQLLocatedError: resolve_hello() takes exactly 4 arguments (2 given)
None
```

May I know if I got mistaken at some place, or the instructions on the website are incomplete?

Thanks

**Comment by patrick91** [comment]
The guide on graphql.org is outdated :)

See http://docs.graphene-python.org/en/latest/quickstart/#creating-a-basic-schema

**Comment by ahujamoh** [comment]
The new example works, thanks. I would request

**Comment by alexisrolland** [comment]
@ahujamoh, on a slightly different note but in case this would be of interest for you, I have put together a tutorial to use Graphene with SQLAlchemy and Flask. Feel free to check it out here: https://github.com/alexisrolland/flask-graphene-sqlalchemy/wiki

**Comment by jkimbo** [comment]
@ahujamoh I'm sure they would appreciate a PR to update their documentation

**Comment by ahujamoh** [comment]
@jkimbo thanks for the idea, raised the PR 👍
