### ISSUE TITLE
ImportError: Could not import 'sixnexus.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: 'module' object has no attribute 'string'.

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene#790]
I have a weird error that is difficult to debug.
```
Internal Server Error: /graphql
Traceback (most recent call last):
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 62, in view
    self = cls(**initkwargs)
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/graphene_django/views.py", line 70, in __init__
    schema = graphene_settings.SCHEMA
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/graphene_django/settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/graphene_django/settings.py", line 60, in perform_import
    return import_from_string(val, setting_name)
  File "/home/ubuntu/sixnexus/.env/local/lib/python2.7/site-packages/graphene_django/settings.py", line 78, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'sixnexus.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: 'module' object has no attribute 'string'.

```

similar but very different error
https://github.com/graphql-python/graphene/issues/343

**Comment by syrusakbary** [comment]
@japrogramer was this caused by Graphene?
