### ISSUE TITLE
Abstract ObjectTypes don't have a specific type.

### ISSUE THREAD

**Issue by Grmiade** [graphql-python/graphene#84]
I have this error, when I add a second inheritance class in my main `Query`.
```
class Query(trainings.schema.Query, brainstormers.schema.Query):
    """This class will inherit from multiple Queries as we begin to add more apps to our project."""

    pass

schema = graphene.Schema(name='MTP Schema')
schema.query = Query
```

**Comment by syrusakbary** [comment]
Are the inherited classes (`trainings.schema.Query` and `brainstormers.schema.Query`) abstract?

By abstract I meant this:
```python
# In trainings/schema.py
class Query(graphene.ObjectType):
    class Meta:
        abstract = True
```

Check this comment in a related issue: https://github.com/graphql-python/graphene/issues/55#issuecomment-160536000
;)

Going to close this issue, but feel free to reopen if is not working for you!

**Comment by Grmiade** [comment]
Yes my classes are abstracts like this.

```
class BrainstormerNode(DjangoNode):

    class Meta:
        model = Brainstormer
        filter_order_by = ['name']


class BrainstormerPropositionGroupNode(DjangoNode):

    class Meta:
        model = BrainstormerPropositionGroup
        filter_order_by = ['name']


class Query(ObjectType):

    class Meta:
        abstract = True

    brainstormer = relay.NodeField(BrainstormerNode)
    all_brainstormer = DjangoFilterConnectionField(BrainstormerNode)

    brainstormer_proposition_group = relay.NodeField(BrainstormerPropositionGroupNode)
    all_brainstormer_proposition_group = DjangoFilterConnectionField(BrainstormerPropositionGroupNode)
```
and
```
class TrainingSessionNode(DjangoNode):

    class Meta:
        model = TrainingSession


class Query(ObjectType):

    class Meta:
        abstract = True

    sessions = relay.NodeField(TrainingSessionNode)
    all_sessions = DjangoFilterConnectionField(TrainingSessionNode)
``` 

An idea ?

**Comment by syrusakbary** [comment]
@Grmiade Can you copy the output of the error here?

**Comment by Grmiade** [comment]
Sure.

```
ERROR Internal Server Error: /graphql
Traceback (most recent call last):
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/django/views/generic/base.py", line 65, in view
    self = cls(**initkwargs)
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/graphene/contrib/django/views.py", line 10, in __init__
    schema=schema.schema,
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/graphene/core/schema.py", line 83, in schema
    query=self.T(self.query),
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/graphene/core/schema.py", line 58, in T
    internal_type = _type.internal_type(self)
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/graphene/core/classtypes/uniontype.py", line 37, in internal_type
    types=list(map(schema.T, cls._meta.types)),
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/graphene/core/schema.py", line 58, in T
    internal_type = _type.internal_type(self)
  File "/Users/jeremyfauvel/.virtualenvs/mtp/lib/python3.4/site-packages/graphene/core/classtypes/objecttype.py", line 91, in internal_type
    raise Exception("Abstract ObjectTypes don't have a specific type.")
Exception: Abstract ObjectTypes don't have a specific type.
```

**Comment by syrusakbary** [comment]
Reopening the issue as the previous fix #55 was invalidated by a major refactor.
This issue will be fixed very soon (few minutes).

**Comment by Grmiade** [comment]
Thanks.

**Comment by syrusakbary** [comment]
A new version of graphene is uploaded to PyPI `0.6.1`... use it and everything should be fine! ;)
https://pypi.python.org/pypi/graphene/0.6.1

**Comment by Grmiade** [comment]
It's work !
So fast ! Thank you so much ;)

**Comment by greenteamer** [comment]
Hello, i have the same 500 error in 0.7.3 version when trying 
`query {
  allNotes {
    edges {
      node {
        id,
        title
      }
    }
  }
}`

**Comment by syrusakbary** [comment]
@greenteamer can you detail a little bit more?

A stacktrace of the Exception or the output of the `/graphql` endpoint when querying could be useful :)

**Comment by greenteamer** [comment]
Traceback (most recent call last):
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/django/views/generic/base.py", line 62, in view
    self = cls(**initkwargs)
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/graphene/contrib/django/views.py", line 10, in __init__
    schema=schema.schema,
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/graphene/core/schema.py", line 86, in schema
    query=self.T(self.query),
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/graphene/core/schema.py", line 61, in T
    internal_type = _type.internal_type(self)
  File "/Users/greenteamer/Desktop/Django/env/monolit/lib/python2.7/site-packages/graphene/core/classtypes/objecttype.py", line 96, in internal_type
    raise Exception("Abstract ObjectTypes don't have a specific type.")
Exception: Abstract ObjectTypes don't have a specific type.

**Comment by syrusakbary** [comment]
@greenteamer The final query type used in the schema should not be abstract.
Try with:
```python
class Query(ObjectType):
    note = relay.NodeField(NotesNode)
    all_notes = DjangoFilterConnectionField(NotesNode)
```

*(without the Meta)*

**Comment by syrusakbary** [comment]
The abstract queries bases should only be used when we inherit the final `Query` type from them.

Example:
```python
class QueryNotes(ObjectType):
    note = relay.NodeField(NotesNode)
    all_notes = DjangoFilterConnectionField(NotesNode)
    class Meta:
         abstract = True

class QueryUsers(ObjectType):
    user = relay.NodeField(UserNote)
    all_users = DjangoFilterConnectionField(UserNote)
    class Meta:
         abstract = True

class Query(QueryNotes, QueryUsers):
    pass

schema = graphene.Schema(name='My Schema')
schema.query = Query
```

**Comment by greenteamer** [comment]
wow ... this is amasing!!! thank you !!! you did a great job

**Comment by jcooz** [comment]
Hi,

I wasn't sure where this comment was best placed.  Which is also in:
https://github.com/graphql-python/graphene/issues/55

I'm attempting to create this level of abstraction as well. I'm using graphql-sqlalchemy and when I do something like:

class UserGroupMember(SQLAlchemyObjectType):
    class Meta:
        abstract = True
        model = UserGroupMemberModel
        interfaces = (CustomNode, )
I'm getting the following error:

TypeError: Invalid attributes: abstract
