### ISSUE TITLE
`tox` tests not working for me

### ISSUE THREAD

**Issue by jhgg** [graphql-python/graphene#9]
Tried to run `tox` but the tests wouldn't load!

```
(graphene)~/P/graphene git:master ❯❯❯ tox                                                                                                                                                               ✱ ◼
GLOB sdist-make: /Users/jake/PycharmProjects/graphene/setup.py
py27 inst-nodeps: /Users/jake/PycharmProjects/graphene/.tox/dist/graphene-0.1.4.zip
py27 installed: blinker==1.4,Django==1.8.5,flake8==2.4.1,graphene==0.1.4,graphql-core==0.1a3,graphql-relay==0.2.0,mccabe==0.3.1,pep8==1.5.7,py==1.4.30,pyflakes==0.8.1,pytest==2.8.2,pytest-django==2.9.1,singledispatch==3.4.0.3,six==1.10.0
py27 runtests: PYTHONHASHSEED='3684720222'
py27 runtests: commands[0] | py.test
Traceback (most recent call last):
  File ".tox/py27/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 38, in main
    config = _prepareconfig(args, plugins)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 117, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 852, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 957, in parse
    self._preparse(args)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 928, in _preparse
    args=args, parser=self._parser)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
    return call_outcome.get_result()
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/pytest_django/plugin.py", line 236, in pytest_load_initial_conftests
    settings.DATABASES
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/jake/PycharmProjects/graphene/.tox/py27/lib/python2.7/site-packages/pytest_django/plugin.py", line 105, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named tests.django_settings

pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
ERROR: InvocationError: '/Users/jake/PycharmProjects/graphene/.tox/py27/bin/py.test'
```

**Comment by syrusakbary** [comment]
Done! :wink:

**Comment by jhgg** [comment]
Yup. That works. Thanks!
