### ISSUE TITLE
Adding type annotations to Meta class causes TypeError

### ISSUE THREAD

**Issue by p7g** [graphql-python/graphene#979]
Adding annotations to the Meta class of an ObjectType causes an Error to be raised.

Minimal reproduction:

```python
import graphene

class Query(graphene.ObjectType):
    class Meta:
        name: str = 'oops'

    hello = graphene.String()

    def resolve_hello(self, info):
        return 'Hello'
    
schema = graphene.Schema(query=Query)
```

This causes the following error when importing the file with Graphene 2.2.0 on Python 3.7.1:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../minimal_repro.py", line 3, in <module>
    class Query(graphene.ObjectType):
  File "/.../.pyenv/versions/3.7.1/lib/python3.7/site-packages/graphene/utils/subclass_with_meta.py", line 52, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "/.../.pyenv/versions/3.7.1/lib/python3.7/site-packages/graphene/types/objecttype.py", line 64, in __init_subclass_with_meta__
    super(ObjectType, cls).__init_subclass_with_meta__(_meta=_meta, **options)
TypeError: __init_subclass_with_meta__() got an unexpected keyword argument '__annotations__'
```

If you remove the `: str` annotation from the name property of Meta, this works just fine.

Without this, any type annotations for mypy, for example, would need to be done with the comment syntax. Not a huge deal, but took some time to debug.

**Comment by ekampf** [comment]
Thanks @p7g !  got a PR in the oven to fix...

**Comment by p7g** [comment]
Works great, thanks for the speedy fix!
